name: Install QLT Local
description: |
  Builds and installs QLT from the local checkout.
inputs:
  go-version:
    description: |
      The Go version to use for building QLT.
    required: false
    default: 'latest'

  add-to-path:
    description: |
      Add QLT to the system path
    required: false
    default: 'true'

outputs:
  qlt-home:
    description: 'The directory containing the QLT installation'
    value: ${{ steps.install-qlt.outputs.qlt-home }}

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install QLT (Local)
      id: install-qlt
      env:
        ADD_TO_PATH: ${{ inputs.add-to-path }}
      shell: bash
      run: |
        echo -e "\e[0;32m[QLT]\e[0m Building and installing QLT from local checkout"

        make install

        QLT_HOME="$(go env GOPATH)/bin"

        if [ "$ADD_TO_PATH" == "true" ]; then
          echo -e "\e[0;32m[QLT]\e[0m Adding '$QLT_HOME' to system path"
          echo "$QLT_HOME" >> $GITHUB_PATH
        fi

        echo -e "\e[0;32m[QLT]\e[0m Setting output parameter qlt-home to $QLT_HOME"
        echo "qlt-home=$QLT_HOME" >> $GITHUB_OUTPUT

        echo -e "\e[0;32m[QLT]\e[0m Done."
