name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    paths:
      - 'internal/archive/**'
      - 'internal/config/**'
      - 'internal/bundle/**'
      - '.clusterfuzzlite/**'
      - '.github/workflows/cflite_pr.yml'
      - 'go.mod'
      - 'go.sum'

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    concurrency:
      group: cflite-pr-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: go
          sanitizer: ${{ matrix.sanitizer }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/clusterfuzzlite-storage.git
          # storage-repo-branch: main
          # storage-repo-branch-coverage: gh-pages
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: 'code-change'
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
          # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/clusterfuzzlite-storage.git
          # storage-repo-branch: main
          # storage-repo-branch-coverage: gh-pages
