name: 🐧 Build Release (Linux x64)

on:
  workflow_call:
    inputs:
      version:
        description: |
          The version to release. (eg: 0.1.2, exclude the 'v'.).
        required: true
        type: string

jobs:
  build-linux64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: |
        mkdir -p dist
        go build \
          -ldflags "-X github.com/trganda/codeql-development-toolkit/cmd.Version=${{ inputs.version }}" \
          -o dist/qlt .
        chmod +x dist/qlt

    - name: Build Archive
      run: |
        ARCHIVE="$(pwd)/qlt-linux-x86_64.zip"
        pushd dist
        zip -r "$ARCHIVE" qlt
        popd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qlt-dist-linux64
        path: qlt-linux-x86_64.zip

    - name: Upload to GitHub Release
      run: gh release upload v${{ inputs.version }} ./qlt-linux-x86_64.zip
      env:
        GH_TOKEN: ${{ github.token }}
