name: 🪟 Build Release (Windows x64)

on:
  workflow_call:
    inputs:
      version:
        description: |
          The version to release. (eg: 0.1.2, exclude the 'v'.).
        required: true
        type: string

jobs:
  build-win64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path dist | Out-Null
        $env:CGO_ENABLED = "0"
        go build `
          -ldflags "-X github.com/trganda/codeql-development-toolkit/cmd.Version=${{ inputs.version }}" `
          -o dist/qlt.exe .

    - name: Build Archive
      shell: pwsh
      run: |
        $ARCHIVE = "$(Get-Location)/qlt-windows-x64.zip"
        Push-Location dist
        Compress-Archive -Path qlt.exe -DestinationPath $ARCHIVE
        Pop-Location

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qlt-dist-win64
        path: qlt-windows-x64.zip

    - name: Upload to GitHub Release
      shell: pwsh
      run: gh release upload v${{ inputs.version }} ./qlt-windows-x64.zip
      env:
        GH_TOKEN: ${{ github.token }}
